In [30]:
#Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../../../Github/Project_banking-fraud-analytics-dashboard-ml-risk/1_Cleaned_Dataset/clean_fraud_df.csv", header=0, index_col=0)

In [ ]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")
df["transaction_hour"] = pd.to_datetime(df["transaction_time"], format="%H:%M", errors="coerce").dt.hour
df["transaction_day"] = df["transaction_date"].dt.day
df["transaction_month"] = df["transaction_date"].dt.month
df["transaction_dayofweek"] = df["transaction_date"].dt.dayofweek

In [43]:

yes_no_cols = [
    "is_international_transaction",
    "is_new_merchant",
    "unusual_time_transaction"
]

for col in yes_no_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

drop_cols = [
    "customer_id	",
    "device_id",
    "ip_address",
    "transaction_time",
    "transaction_date"
]

df = df.drop(columns=drop_cols, errors="ignore")
df

,transaction_amount_in_million,transaction_type,merchant_id,merchant_category,transaction_location,customer_home_location,distance_from_home,card_type,account_balance_in_million,daily_transaction_count,...,avg_transaction_amount_in_million,max_transaction_last_24h_in_million,is_international_transaction,is_new_merchant,failed_transaction_count,unusual_time_transaction,previous_fraud_count,fraud_label,Country_x,Country_y
customer_id,,,,,,,,,,,,,,,,,,,,,
24239.0,6.0,POS,97028.0,ATM,singapore,lahore,466.0,Credit,30.0,4.0,...,2.0,4.0,NaN,NaN,0.0,NaN,1.0,Normal,Singapore,Pakistan
77250.0,9.0,ATM,27515.0,ATM,singapore,lahore,215.0,Credit,4.0,4.0,...,5.0,8.0,NaN,NaN,1.0,NaN,1.0,Normal,Singapore,Pakistan
34294.0,3.0,POS,13810.0,Electronics,faisalabad,faisalabad,216.0,Debit,38.0,5.0,...,5.0,8.0,NaN,NaN,0.0,NaN,1.0,Normal,Pakistan,Pakistan
92041.0,1.0,Online,10501.0,Grocery,london,karachi,408.0,Debit,22.0,6.0,...,5.0,1.0,NaN,NaN,2.0,NaN,1.0,Normal,United Kingdom,Pakistan
71578.0,1.0,Online,53569.0,Electronics,singapore,islamabad,209.0,Debit,10.0,3.0,...,4.0,3.0,NaN,NaN,1.0,NaN,1.0,Normal,Singapore,Pakistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87401.0,4.0,POS,13857.0,Clothing,faisalabad,islamabad,571.0,Credit,34.0,1.0,...,4.0,2.0,NaN,NaN,1.0,NaN,0.0,Fraud,Pakistan,Pakistan
65425.0,4.0,Online,25552.0,Electronics,faisalabad,multan,433.0,Credit,4.0,4.0,...,1.0,6.0,NaN,NaN,2.0,NaN,0.0,Normal,Pakistan,Pakistan
14318.0,9.0,Online,41771.0,Electronics,singapore,lahore,161.0,Debit,21.0,5.0,...,4.0,2.0,NaN,NaN,0.0,NaN,1.0,Fraud,Singapore,Pakistan
55757.0,1.0,Online,72485.0,Clothing,bangkok,karachi,317.0,Credit,39.0,3.0,...,2.0,1.0,NaN,NaN,0.0,NaN,1.0,Normal,Thailand,Pakistan
57274.0,7.0,ATM,69446.0,Restaurant,bangkok,islamabad,494.0,Debit,23.0,3.0,...,3.0,2.0,NaN,NaN,0.0,NaN,1.0,Normal,Thailand,Pakistan

In [60]:
#only run code once, otherwise more and more indexes will be added to the DF
#df = df.reset_index()
#df

In [79]:
#df = df.drop(["index", "customer_id", "unusual_time_transaction", "is_new_merchant", "is_international_transaction"], axis=1)
df = df.drop(["previous_fraud_count"], axis=1)
df

,transaction_amount_in_million,transaction_type,merchant_id,merchant_category,transaction_location,customer_home_location,distance_from_home,card_type,account_balance_in_million,daily_transaction_count,weekly_transaction_count,avg_transaction_amount_in_million,max_transaction_last_24h_in_million,failed_transaction_count,fraud_label,Country_x,Country_y
0,6.0,POS,97028.0,ATM,singapore,lahore,466.0,Credit,30.0,4.0,17.0,2.0,4.0,0.0,Normal,Singapore,Pakistan
1,9.0,ATM,27515.0,ATM,singapore,lahore,215.0,Credit,4.0,4.0,9.0,5.0,8.0,1.0,Normal,Singapore,Pakistan
2,3.0,POS,13810.0,Electronics,faisalabad,faisalabad,216.0,Debit,38.0,5.0,18.0,5.0,8.0,0.0,Normal,Pakistan,Pakistan
3,1.0,Online,10501.0,Grocery,london,karachi,408.0,Debit,22.0,6.0,18.0,5.0,1.0,2.0,Normal,United Kingdom,Pakistan
4,1.0,Online,53569.0,Electronics,singapore,islamabad,209.0,Debit,10.0,3.0,18.0,4.0,3.0,1.0,Normal,Singapore,Pakistan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49848,4.0,POS,13857.0,Clothing,faisalabad,islamabad,571.0,Credit,34.0,1.0,5.0,4.0,2.0,1.0,Fraud,Pakistan,Pakistan
49849,4.0,Online,25552.0,Electronics,faisalabad,multan,433.0,Credit,4.0,4.0,7.0,1.0,6.0,2.0,Normal,Pakistan,Pakistan
49850,9.0,Online,41771.0,Electronics,singapore,lahore,161.0,Debit,21.0,5.0,15.0,4.0,2.0,0.0,Fraud,Singapore,Pakistan
49851,1.0,Online,72485.0,Clothing,bangkok,karachi,317.0,Credit,39.0,3.0,20.0,2.0,1.0,0.0,Normal,Thailand,Pakistan
49852,7.0,ATM,69446.0,Restaurant,bangkok,islamabad,494.0,Debit,23.0,3.0,18.0,3.0,2.0,0.0,Normal,Thailand,Pakistan

In [75]:
#Step 4: Split data - Train-Test Split
from sklearn.model_selection import train_test_split


x = df.drop(columns=["fraud_label"])
y = df["fraud_label"]
#print(x.head(1))
#print(y.head(1))


x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Train target ratio:")
print(y_train.value_counts(normalize=True))
print("Test target ration:")
print(y_test.value_counts(normalize=True))

Train target ratio:
fraud_label
Normal    0.951507
Fraud     0.048493
Name: proportion, dtype: float64
Test target ration:
fraud_label
Normal    0.95156
Fraud     0.04844
Name: proportion, dtype: float64

In [84]:
#Step 6: Building a preprocessing (separating numerical from categorical columns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric_cols = x_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = x_train.select_dtypes(include=["object", "category"]).columns.tolist()

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_cols),
    ("cat", categorical_pipeline, categorical_cols)
])

In [ ]:
#splitting the features and targets
X = df.drop(columns=["fraud_label"])
y = df["fraud_label"]